
package org.jboss.as.quickstarts.kitchensink.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.7
 * Thu Apr 15 17:26:07 CEST 2021
 * Generated source version: 3.3.7
 */

@XmlRootElement(name = "createMemberResponse", namespace = "http://ws.kitchensink.quickstarts.as.jboss.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createMemberResponse", namespace = "http://ws.kitchensink.quickstarts.as.jboss.org/")

public class CreateMemberResponse {


}

