
package org.jboss.as.quickstarts.kitchensink.ws.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.3.7
 * Fri Apr 16 09:06:25 CEST 2021
 * Generated source version: 3.3.7
 */

@XmlRootElement(name = "getAllMembersResponse", namespace = "http://ws.kitchensink.quickstarts.as.jboss.org/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllMembersResponse", namespace = "http://ws.kitchensink.quickstarts.as.jboss.org/")

public class GetAllMembersResponse {

    @XmlElement(name = "return")
    private java.util.List<org.jboss.as.quickstarts.kitchensink.model.Member> _return;

    public java.util.List<org.jboss.as.quickstarts.kitchensink.model.Member> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<org.jboss.as.quickstarts.kitchensink.model.Member> new_return)  {
        this._return = new_return;
    }

}

